version: "2"
services:
  express-app:
    container_name: funbun-be-api
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
